export const SITE_FETCH_SUCCESS = "SITE_FETCH_SUCCESS";
export const EVENTS_FETCH_SUCCESS = "EVENTS_FETCH_SUCCESS";
export const GET_USER = "GET_USER";
export const LOADING_DATA = "LOADING_DATA";
export const ERROR = "ERROR";
export const SET_SEARCHED_TEXT = "SET_SEARCHED_TEXT";
